In [1]:
#Edgar Moises Hernandez-Gonzalez
#18/06/19
#Clasificacion de EEG con diferentes clasificadores

In [2]:
import pandas as pd
from sklearn.model_selection import cross_val_score

In [3]:
#9 clasificadores
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier

C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [4]:
datos = pd.read_csv("CaracteristicasSuj15.csv", header=None)
x = datos.iloc[:, 0:54].values
y = datos.iloc[:, 54].values
print(x.shape)
print(y.shape)

(181, 54)
(181,)


In [5]:
clf1 = SVC()
print(clf1)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


In [6]:
clf2 = LinearSVC()
print(clf2)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)


In [7]:
clf3 = KNeighborsClassifier()
print(clf3)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')


In [8]:
clf4 = LogisticRegression()
print(clf4)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)


In [9]:
clf5 = DecisionTreeClassifier()
print(clf5)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')


In [10]:
clf6 = GaussianNB()
print(clf6)

GaussianNB(priors=None)


In [11]:
clf7 = LinearDiscriminantAnalysis()
print(clf7)

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)


In [12]:
clf8 = QuadraticDiscriminantAnalysis()
print(clf8)

QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
               store_covariance=False, store_covariances=None, tol=0.0001)


In [13]:
clf9 = RandomForestClassifier()
print(clf9)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)


In [14]:
puntuaciones = cross_val_score(clf1, x, y, cv = 5)
print(puntuaciones)
print("SVM:", puntuaciones.mean())

[0.17948718 0.16216216 0.16666667 0.16666667 0.18181818]
SVM: 0.17136017136017134


In [15]:
puntuaciones = cross_val_score(clf2, x, y, cv = 5)
print(puntuaciones)
print("SVM Lineal:", puntuaciones.mean())

[0.17948718 0.21621622 0.16666667 0.13888889 0.18181818]
SVM Lineal: 0.17661542661542665


In [16]:
puntuaciones = cross_val_score(clf3, x, y, cv = 5)
print(puntuaciones)
print("K-NN:", puntuaciones.mean())

[0.23076923 0.16216216 0.11111111 0.22222222 0.15151515]
K-NN: 0.17555597555597555


In [17]:
puntuaciones = cross_val_score(clf4, x, y, cv = 5)
print(puntuaciones)
print("Regresion Logistica:", puntuaciones.mean())

[0.17948718 0.13513514 0.16666667 0.19444444 0.09090909]
Regresion Logistica: 0.1533285033285033


In [18]:
puntuaciones = cross_val_score(clf5, x, y, cv = 5)
print(puntuaciones)
print("Arbol de decision:", puntuaciones.mean())

[0.25641026 0.2972973  0.27777778 0.13888889 0.09090909]
Arbol de decision: 0.21225666225666226


In [19]:
puntuaciones = cross_val_score(clf6, x, y, cv = 5)
print(puntuaciones)
print("Naive Bayes:", puntuaciones.mean())

[0.07692308 0.16216216 0.13888889 0.13888889 0.12121212]
Naive Bayes: 0.1276150276150276


In [20]:
puntuaciones = cross_val_score(clf7, x, y, cv = 5)
print(puntuaciones)
print("LDA:", puntuaciones.mean())

[0.1025641  0.10810811 0.16666667 0.22222222 0.18181818]
LDA: 0.1562758562758563


In [21]:
puntuaciones = cross_val_score(clf8, x, y, cv = 5)
print(puntuaciones)
print("QDA:", puntuaciones.mean())

[0.15384615 0.27027027 0.16666667 0.22222222 0.06060606]
QDA: 0.1747222747222747


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [22]:
puntuaciones = cross_val_score(clf9, x, y, cv = 5)
print(puntuaciones)
print("RF:", puntuaciones.mean())

[0.20512821 0.13513514 0.22222222 0.11111111 0.12121212]
RF: 0.15896175896175896
