In [1]:
#Edgar Moises Hernandez-Gonzalez
#17/06/19-18/06/19
#Red Neuronal con conjunto de entrenamiento y conjunto de prueba

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

In [3]:
#datos para la red neuronal
datos = pd.read_csv("CaracteristicasSuj01.csv", header=None)
x = datos.iloc[:, 0:54].values
y = datos.iloc[:, 54].values
print(x.shape)
print(y.shape)
xEntrenar, xPruebas, yEntrenar, yPruebas = train_test_split(x, y)

(132, 54)
(132,)


In [4]:
clf = MLPClassifier()
print(clf)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)


In [5]:
clf.fit(xEntrenar, yEntrenar)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [6]:
clf.score(xPruebas, yPruebas)

0.2727272727272727

In [7]:
#matriz de confusion
matriz = confusion_matrix(y, clf.predict(x))
print(matriz)

[[ 9  0 11  0  1  0]
 [12  1 11  2  0  2]
 [10  0  8  1  3  0]
 [ 8  0  5  0  1  1]
 [ 7  0 11  0  3  4]
 [ 7  0 12  0  1  1]]


In [8]:
matrizTest = confusion_matrix(yPruebas, clf.predict(xPruebas))
print(matrizTest)

[[2 0 2 0 1 0]
 [4 0 5 0 0 0]
 [1 0 4 0 1 0]
 [2 0 0 0 0 0]
 [0 0 2 0 3 1]
 [1 0 4 0 0 0]]
